# Generated by Django 5.1.1 on 2024-10-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='haveShop',
            field=models.BooleanField(default=False),
        ),
    ]
