# Generated by Django 5.2.15 on 2026-06-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='directory_p_name_d60140_idx',
            old_name='directory_p_name_8f6953_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='directory_p_status_f6f3b3_idx',
            old_name='directory_p_status_89a5d_idx',
        ),
    ]
